Repository Skythrill256/Flappy-Bird, pull requests merged in 2025-03, with the labels that each got.

#2 Fixed issue #1: Added High score feature
  index.html
  script.js
  style.css
Labels: good first issue, apertre2.0, easy

#10 improved ui of homepage
  index.html
  script.js
  style.css
Labels: apertre2.0, easy

#15 Game over popup UI improved
  index.html
  script.js
  style.css
Labels: apertre2.0, easy

#12 Added README.md file with setup and run commands
  README.md
Labels: apertre2.0, doc

#16 Implement pause and resume functionality in the game
  script.js
Labels: apertre2.0, easy
